# Generated by Django 6.0.6 on 2026-07-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendances", "0001_initial"),
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attendance",
            name="unique_attendance_pe_day",
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "date"), name="unique_attendance_per_day"
            ),
        ),
    ]
