# Generated by Django 6.0.6 on 2026-07-29 12:20

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    groups = [
        "Employee",
        "Student",
        "Teacher",
    ]

    for name in groups:
        Group.objects.get_or_create(name=name)

def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    Group.objects.filter(
        name__in=[
            "Employee",
            "Student",
            "Teacher"
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length")
    ]

    operations = [
        migrations.RunPython(
            create_groups,
            delete_groups
        ),
    ]
