# Generated by Django 6.0.6 on 2026-07-29 12:28

from django.db import migrations

def assign_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    employee = Group.objects.get(name="Employee")
    teacher = Group.objects.get(name="Teacher")
    student = Group.objects.get(name="Student")

    # Employee
    employee_permissions = Permission.objects.filter(
        content_type__app_label__in=[
            "profiles",
            "courses",
            "enrollments",
            "attendance",
            "exams",
        ]
    )

    employee.permissions.set(employee_permissions)

    # Teacher
    teacher_permissions = Permission.objects.filter(
        codename__in=[
            "view_studentprofile",

            "view_course",
            "view_section",

            "view_enrollment",

            "view_attendance",
            "add_attendance",
            "change_attendance",

            "view_exam",
            "add_exam",
            "change_exam",

            "view_grade",
            "add_grade",
            "change_grade",
        ]
    )
    teacher.permissions.set(teacher_permissions)

    # Student
    student_permissions = Permission.objects.filter(
        codename__in=[
            "view_studentprofile",
            "view_course",
            "view_section",
            "view_enrollment",
            "view_attendance",
            "view_exam",
            "view_grade",
        ]
    )

    student.permissions.set(student_permissions)

def remove_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    for name in [
        "Employee",
        "Teacher",
        "Student",
    ]:
        group = Group.objects.get(name=name)
        group.permissions.clear()

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_create_default_groups"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(
            assign_permissions,
            remove_permissions,
        ),
    ]
